### ISSUE TITLE
Feature request: Shadertoy versions

### ISSUE THREAD

**Issue by nlguillemot** [stegu/webgl-noise#1]
It would be great to have these noise demos on Shadertoy, to make it easier to see them and play with them.

**Comment by stegu** [comment]
Good idea. I'll try to find the time to make some inspiring 2D demos, at least.

For 3D, I'm not fond of Shadertoy's lack of polygon-based geometry. In fact, I think it's downright stupid, because it calls for a strange and awkward style of programming that is not representative of real world uses of GLSL. Using fragment-based raytracing to draw a sphere is not the way a GPU of today is designed to work, and it's definitely not the way you would do it in a real OpenGL application. It wastes tremendous amounts of GPU processing power, and any 3D noise demo tends to get lost in geometry-related code instead of focusing on the surface pattern.

But yes, putting some example uses of my noise code on Shadertoy is a good idea. Thanks for the suggestion.

**Comment by nlguillemot** [comment]
At this point, any interactive WebGL implementation would make it easier to study these noise functions.

**Comment by stegu** [comment]
I hear you. It should be a reasonably easy task to port some of my existing binary demos to WebGL. I will try to also provide a small sandbox to test the functions on 2D and 3D shapes by editing the shader in a text field. I should be able to find the time to do this soon.

**Comment by stegu** [comment]
Seeing how I have not found the time to do a WebGL sandbox demo for several years, I need to face the fact that I will never find the time to do it. However, all these functions are WebGL compatible, and Shadertoy will accept them being included in your fragment shader code. Closing the issue.

**Comment by redblobgames** [comment]
There's now a demo of some of the noise functions, along with code you can copy into Shadertoy, here: http://stegu.github.io/webgl-noise/webdemo/
