### ISSUE TITLE
Patent protection

### ISSUE THREAD

**Issue by cypherdare** [stegu/webgl-noise#4]
It would be helpful to clarify in the readme whether or not the 3D and 4D simplex noise functions use the implementation covered by Perlin's U.S. Patent 6,867,776.

**Comment by stegu** [comment]
The header doesn't mention it because I honestly don't know.

I am not a lawyer, and I am vehemently opposed to software patents because
I see them have a chilling effect on innovation, in direct contradiction to
the purpose of patents, but the implementation is probably similar enough
to Ken Perlin's version that a patent lawyer could find infringement. The
hash and the gradients are different and unique to our implementation, but
the simplex grid and the interpolation kernels are the same.

This could possibly be worked around, but it would still be a gray zone.
Lawyers' interpretations of legal documents describing technology in
circumspect and intentionally vague and obfuscated terms never make much
sense to me.

It hurts to say it, but with the recent overreach and preposterous
proliferation of patent troll lawsuits, I would advise caution. You might
want to have a chat with a patent lawyer and perhaps send a licensing
request to the patent holder, whoever that might be after the circus around
Nokia the past few years.

  /Stefan Gustavson

**Comment by stegu** [comment]
The aforementioned patent, now owned by a patent troll company named "Wsou Investments LLC", will expire in 2022, so this entire patent debacle will soon, finally, be a moot point.

Since I first saw this patent, I am convinced that it would fall flat on its face if it was challenged for validity by any competent party, but it would be prohibitilvely expensive to prove that in court.

Just to give you an idea of how ridiculous the patent is, below is the "summary of the invention" in legalese. It is a sad bunch of boilerplate claims in order to pretend that this is a "device" and a "method", and not just a computer program. As with all software patents granted during the time period when US patent law explicitly disallowed patents on algorithms and computer programs "as such", this is an algorithm described in obfuscated legalese by a patent lawyer, trying desperately to pretend that it comprises patentable subject matter.

Incidentally, the summary is even fundamentally wrong in the only case where it goes into any specifics. The texture does have visible grid artifacts, just less visible than the classic Perlin noise algorithm, and not axis-aligned with the extrinsic (x,y,z) coordinate grid.

(quote)

SUMMARY OF THE INVENTION

The present invention pertains to an apparatus for generating an image. The apparatus comprises a computer. The apparatus comprises a display connected to the computer upon which images from the computer appear. The apparatus comprises a mechanism for producing images with texture that do not have visible grid artifacts, the producing mechanism disposed in the computer.

The present invention pertains to a method for generating images. The method comprises the steps of producing the images with texture that do not have visible grid artifacts with the computer. There is the step of displaying the images on a display. Preferably, there is the step of introducing information into the computer from which the images are produced.

(end quote)

"Preferably, there is the step of introducing information into the computer from which the images are produced." What does that even mean? Gobbledygook. Sheesh.

**Comment by stegu** [comment]
Keeping this issue open at least until the sad and ugly patent expires.

**Comment by stegu** [comment]
Now counting the days until the patent expires. If software patents are to be allowed (and I strongly oppose the very idea), a duration of 20 years is much too long.

**Comment by Kry-Vosa** [comment]
I would like to remind You this issue can be finally closed! Happy days.

**Comment by stegu** [comment]
Thanks for the reminder. Good riddance. My hope is that patent trolls everywhere turn to stone by exposure to sunlight instead of being allowed to leech on real innovators, and that we will find a way to stop large corporations from using irrelevant or overreaching patents to unjustly bully small competitors into submission.
Closing the issue with a sour aftertaste. Simplex noise was a great idea that has been held back for decades by that truly ugly patent.
